# CI de Nível 01 - Disparo manual a partir de 1 clique
name: 'CI Execução Manual - Testes WEB'

# Gatilho para execução manual
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      # Passo 1 - Check out do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Passo 2 - Instalação do Node.js
      - name: Instalando Node.js
        uses: actions/setup-node@v4
        #with:
          #node-version: '20.16.0'

      # Passo 3 - Instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # Passo 4 - Instalação de dependências do projeto
      - name: Instalando dependências
        run: cd automacao-web-pgats 
        yarn install

      # Passo 5 - Executando testes E2E (end-to-end)
      - name: Teste E2E (end-to-end)
        run: yarn test

      # Passo 6 - Gerando relatório de teste
      - name: Upload do relatório de testes
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: ./cypress-report